apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
  selector:
    {{- include "bff.selectorLabels" . | nindent 4 }}
